/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_management_service.h"
#include "storage_management_service.tcc"

namespace jiffy { namespace storage {


storage_management_service_create_partition_args::~storage_management_service_create_partition_args() noexcept {
}


storage_management_service_create_partition_pargs::~storage_management_service_create_partition_pargs() noexcept {
}


storage_management_service_create_partition_result::~storage_management_service_create_partition_result() noexcept {
}


storage_management_service_create_partition_presult::~storage_management_service_create_partition_presult() noexcept {
}


storage_management_service_setup_chain_args::~storage_management_service_setup_chain_args() noexcept {
}


storage_management_service_setup_chain_pargs::~storage_management_service_setup_chain_pargs() noexcept {
}


storage_management_service_setup_chain_result::~storage_management_service_setup_chain_result() noexcept {
}


storage_management_service_setup_chain_presult::~storage_management_service_setup_chain_presult() noexcept {
}


storage_management_service_destroy_partition_args::~storage_management_service_destroy_partition_args() noexcept {
}


storage_management_service_destroy_partition_pargs::~storage_management_service_destroy_partition_pargs() noexcept {
}


storage_management_service_destroy_partition_result::~storage_management_service_destroy_partition_result() noexcept {
}


storage_management_service_destroy_partition_presult::~storage_management_service_destroy_partition_presult() noexcept {
}


storage_management_service_get_path_args::~storage_management_service_get_path_args() noexcept {
}


storage_management_service_get_path_pargs::~storage_management_service_get_path_pargs() noexcept {
}


storage_management_service_get_path_result::~storage_management_service_get_path_result() noexcept {
}


storage_management_service_get_path_presult::~storage_management_service_get_path_presult() noexcept {
}


storage_management_service_sync_args::~storage_management_service_sync_args() noexcept {
}


storage_management_service_sync_pargs::~storage_management_service_sync_pargs() noexcept {
}


storage_management_service_sync_result::~storage_management_service_sync_result() noexcept {
}


storage_management_service_sync_presult::~storage_management_service_sync_presult() noexcept {
}


storage_management_service_dump_args::~storage_management_service_dump_args() noexcept {
}


storage_management_service_dump_pargs::~storage_management_service_dump_pargs() noexcept {
}


storage_management_service_dump_result::~storage_management_service_dump_result() noexcept {
}


storage_management_service_dump_presult::~storage_management_service_dump_presult() noexcept {
}


storage_management_service_load_args::~storage_management_service_load_args() noexcept {
}


storage_management_service_load_pargs::~storage_management_service_load_pargs() noexcept {
}


storage_management_service_load_result::~storage_management_service_load_result() noexcept {
}


storage_management_service_load_presult::~storage_management_service_load_presult() noexcept {
}


storage_management_service_storage_capacity_args::~storage_management_service_storage_capacity_args() noexcept {
}


storage_management_service_storage_capacity_pargs::~storage_management_service_storage_capacity_pargs() noexcept {
}


storage_management_service_storage_capacity_result::~storage_management_service_storage_capacity_result() noexcept {
}


storage_management_service_storage_capacity_presult::~storage_management_service_storage_capacity_presult() noexcept {
}


storage_management_service_storage_size_args::~storage_management_service_storage_size_args() noexcept {
}


storage_management_service_storage_size_pargs::~storage_management_service_storage_size_pargs() noexcept {
}


storage_management_service_storage_size_result::~storage_management_service_storage_size_result() noexcept {
}


storage_management_service_storage_size_presult::~storage_management_service_storage_size_presult() noexcept {
}


storage_management_service_resend_pending_args::~storage_management_service_resend_pending_args() noexcept {
}


storage_management_service_resend_pending_pargs::~storage_management_service_resend_pending_pargs() noexcept {
}


storage_management_service_resend_pending_result::~storage_management_service_resend_pending_result() noexcept {
}


storage_management_service_resend_pending_presult::~storage_management_service_resend_pending_presult() noexcept {
}


storage_management_service_forward_all_args::~storage_management_service_forward_all_args() noexcept {
}


storage_management_service_forward_all_pargs::~storage_management_service_forward_all_pargs() noexcept {
}


storage_management_service_forward_all_result::~storage_management_service_forward_all_result() noexcept {
}


storage_management_service_forward_all_presult::~storage_management_service_forward_all_presult() noexcept {
}


storage_management_service_update_partition_data_args::~storage_management_service_update_partition_data_args() noexcept {
}


storage_management_service_update_partition_data_pargs::~storage_management_service_update_partition_data_pargs() noexcept {
}


storage_management_service_update_partition_data_result::~storage_management_service_update_partition_data_result() noexcept {
}


storage_management_service_update_partition_data_presult::~storage_management_service_update_partition_data_presult() noexcept {
}

}} // namespace

