/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "directory_service.h"
#include "directory_service.tcc"

namespace jiffy { namespace directory {


directory_service_create_directory_args::~directory_service_create_directory_args() noexcept {
}


directory_service_create_directory_pargs::~directory_service_create_directory_pargs() noexcept {
}


directory_service_create_directory_result::~directory_service_create_directory_result() noexcept {
}


directory_service_create_directory_presult::~directory_service_create_directory_presult() noexcept {
}


directory_service_create_directories_args::~directory_service_create_directories_args() noexcept {
}


directory_service_create_directories_pargs::~directory_service_create_directories_pargs() noexcept {
}


directory_service_create_directories_result::~directory_service_create_directories_result() noexcept {
}


directory_service_create_directories_presult::~directory_service_create_directories_presult() noexcept {
}


directory_service_open_args::~directory_service_open_args() noexcept {
}


directory_service_open_pargs::~directory_service_open_pargs() noexcept {
}


directory_service_open_result::~directory_service_open_result() noexcept {
}


directory_service_open_presult::~directory_service_open_presult() noexcept {
}


directory_service_create_args::~directory_service_create_args() noexcept {
}


directory_service_create_pargs::~directory_service_create_pargs() noexcept {
}


directory_service_create_result::~directory_service_create_result() noexcept {
}


directory_service_create_presult::~directory_service_create_presult() noexcept {
}


directory_service_open_or_create_args::~directory_service_open_or_create_args() noexcept {
}


directory_service_open_or_create_pargs::~directory_service_open_or_create_pargs() noexcept {
}


directory_service_open_or_create_result::~directory_service_open_or_create_result() noexcept {
}


directory_service_open_or_create_presult::~directory_service_open_or_create_presult() noexcept {
}


directory_service_exists_args::~directory_service_exists_args() noexcept {
}


directory_service_exists_pargs::~directory_service_exists_pargs() noexcept {
}


directory_service_exists_result::~directory_service_exists_result() noexcept {
}


directory_service_exists_presult::~directory_service_exists_presult() noexcept {
}


directory_service_last_write_time_args::~directory_service_last_write_time_args() noexcept {
}


directory_service_last_write_time_pargs::~directory_service_last_write_time_pargs() noexcept {
}


directory_service_last_write_time_result::~directory_service_last_write_time_result() noexcept {
}


directory_service_last_write_time_presult::~directory_service_last_write_time_presult() noexcept {
}


directory_service_set_permissions_args::~directory_service_set_permissions_args() noexcept {
}


directory_service_set_permissions_pargs::~directory_service_set_permissions_pargs() noexcept {
}


directory_service_set_permissions_result::~directory_service_set_permissions_result() noexcept {
}


directory_service_set_permissions_presult::~directory_service_set_permissions_presult() noexcept {
}


directory_service_get_permissions_args::~directory_service_get_permissions_args() noexcept {
}


directory_service_get_permissions_pargs::~directory_service_get_permissions_pargs() noexcept {
}


directory_service_get_permissions_result::~directory_service_get_permissions_result() noexcept {
}


directory_service_get_permissions_presult::~directory_service_get_permissions_presult() noexcept {
}


directory_service_remove_args::~directory_service_remove_args() noexcept {
}


directory_service_remove_pargs::~directory_service_remove_pargs() noexcept {
}


directory_service_remove_result::~directory_service_remove_result() noexcept {
}


directory_service_remove_presult::~directory_service_remove_presult() noexcept {
}


directory_service_remove_all_args::~directory_service_remove_all_args() noexcept {
}


directory_service_remove_all_pargs::~directory_service_remove_all_pargs() noexcept {
}


directory_service_remove_all_result::~directory_service_remove_all_result() noexcept {
}


directory_service_remove_all_presult::~directory_service_remove_all_presult() noexcept {
}


directory_service_sync_args::~directory_service_sync_args() noexcept {
}


directory_service_sync_pargs::~directory_service_sync_pargs() noexcept {
}


directory_service_sync_result::~directory_service_sync_result() noexcept {
}


directory_service_sync_presult::~directory_service_sync_presult() noexcept {
}


directory_service_dump_args::~directory_service_dump_args() noexcept {
}


directory_service_dump_pargs::~directory_service_dump_pargs() noexcept {
}


directory_service_dump_result::~directory_service_dump_result() noexcept {
}


directory_service_dump_presult::~directory_service_dump_presult() noexcept {
}


directory_service_load_args::~directory_service_load_args() noexcept {
}


directory_service_load_pargs::~directory_service_load_pargs() noexcept {
}


directory_service_load_result::~directory_service_load_result() noexcept {
}


directory_service_load_presult::~directory_service_load_presult() noexcept {
}


directory_service_rename_args::~directory_service_rename_args() noexcept {
}


directory_service_rename_pargs::~directory_service_rename_pargs() noexcept {
}


directory_service_rename_result::~directory_service_rename_result() noexcept {
}


directory_service_rename_presult::~directory_service_rename_presult() noexcept {
}


directory_service_status_args::~directory_service_status_args() noexcept {
}


directory_service_status_pargs::~directory_service_status_pargs() noexcept {
}


directory_service_status_result::~directory_service_status_result() noexcept {
}


directory_service_status_presult::~directory_service_status_presult() noexcept {
}


directory_service_directory_entries_args::~directory_service_directory_entries_args() noexcept {
}


directory_service_directory_entries_pargs::~directory_service_directory_entries_pargs() noexcept {
}


directory_service_directory_entries_result::~directory_service_directory_entries_result() noexcept {
}


directory_service_directory_entries_presult::~directory_service_directory_entries_presult() noexcept {
}


directory_service_recursive_directory_entries_args::~directory_service_recursive_directory_entries_args() noexcept {
}


directory_service_recursive_directory_entries_pargs::~directory_service_recursive_directory_entries_pargs() noexcept {
}


directory_service_recursive_directory_entries_result::~directory_service_recursive_directory_entries_result() noexcept {
}


directory_service_recursive_directory_entries_presult::~directory_service_recursive_directory_entries_presult() noexcept {
}


directory_service_dstatus_args::~directory_service_dstatus_args() noexcept {
}


directory_service_dstatus_pargs::~directory_service_dstatus_pargs() noexcept {
}


directory_service_dstatus_result::~directory_service_dstatus_result() noexcept {
}


directory_service_dstatus_presult::~directory_service_dstatus_presult() noexcept {
}


directory_service_add_tags_args::~directory_service_add_tags_args() noexcept {
}


directory_service_add_tags_pargs::~directory_service_add_tags_pargs() noexcept {
}


directory_service_add_tags_result::~directory_service_add_tags_result() noexcept {
}


directory_service_add_tags_presult::~directory_service_add_tags_presult() noexcept {
}


directory_service_is_regular_file_args::~directory_service_is_regular_file_args() noexcept {
}


directory_service_is_regular_file_pargs::~directory_service_is_regular_file_pargs() noexcept {
}


directory_service_is_regular_file_result::~directory_service_is_regular_file_result() noexcept {
}


directory_service_is_regular_file_presult::~directory_service_is_regular_file_presult() noexcept {
}


directory_service_is_directory_args::~directory_service_is_directory_args() noexcept {
}


directory_service_is_directory_pargs::~directory_service_is_directory_pargs() noexcept {
}


directory_service_is_directory_result::~directory_service_is_directory_result() noexcept {
}


directory_service_is_directory_presult::~directory_service_is_directory_presult() noexcept {
}


directory_service_reslove_failures_args::~directory_service_reslove_failures_args() noexcept {
}


directory_service_reslove_failures_pargs::~directory_service_reslove_failures_pargs() noexcept {
}


directory_service_reslove_failures_result::~directory_service_reslove_failures_result() noexcept {
}


directory_service_reslove_failures_presult::~directory_service_reslove_failures_presult() noexcept {
}


directory_service_add_replica_to_chain_args::~directory_service_add_replica_to_chain_args() noexcept {
}


directory_service_add_replica_to_chain_pargs::~directory_service_add_replica_to_chain_pargs() noexcept {
}


directory_service_add_replica_to_chain_result::~directory_service_add_replica_to_chain_result() noexcept {
}


directory_service_add_replica_to_chain_presult::~directory_service_add_replica_to_chain_presult() noexcept {
}


directory_service_add_data_block_args::~directory_service_add_data_block_args() noexcept {
}


directory_service_add_data_block_pargs::~directory_service_add_data_block_pargs() noexcept {
}


directory_service_add_data_block_result::~directory_service_add_data_block_result() noexcept {
}


directory_service_add_data_block_presult::~directory_service_add_data_block_presult() noexcept {
}


directory_service_remove_data_block_args::~directory_service_remove_data_block_args() noexcept {
}


directory_service_remove_data_block_pargs::~directory_service_remove_data_block_pargs() noexcept {
}


directory_service_remove_data_block_result::~directory_service_remove_data_block_result() noexcept {
}


directory_service_remove_data_block_presult::~directory_service_remove_data_block_presult() noexcept {
}


directory_service_request_partition_data_update_args::~directory_service_request_partition_data_update_args() noexcept {
}


directory_service_request_partition_data_update_pargs::~directory_service_request_partition_data_update_pargs() noexcept {
}


directory_service_request_partition_data_update_result::~directory_service_request_partition_data_update_result() noexcept {
}


directory_service_request_partition_data_update_presult::~directory_service_request_partition_data_update_presult() noexcept {
}


directory_service_get_storage_capacity_args::~directory_service_get_storage_capacity_args() noexcept {
}


directory_service_get_storage_capacity_pargs::~directory_service_get_storage_capacity_pargs() noexcept {
}


directory_service_get_storage_capacity_result::~directory_service_get_storage_capacity_result() noexcept {
}


directory_service_get_storage_capacity_presult::~directory_service_get_storage_capacity_presult() noexcept {
}

}} // namespace

